### ISSUE TITLE
魔改不用矿辞的吗？

### ISSUE THREAD

**Issue by friendlyhj** [dong031001/ET-Mariphilia#4]
看见\<mekanism:nugget:6\>啥的浑身难受，即使有相关mod统一矿辞，也应该用\<ore:nuggetCopper\>之类的。

而且，在之后cot材料系统添加物品这会吃大亏的。

**Comment by dong031001** [comment]
看清楚一下，这是输出，不支持IIngredient

**Comment by friendlyhj** [comment]
即使不支持IIngredient，也应该用`firstItem` Getter将矿辞转换为IItemStack。

**Comment by dong031001** [comment]
感谢建议，理应如此

**Comment by dong031001** [comment]
已经实现，参考util/oreDictUtils.zs中的静态方法
